(function () {
  const phases = [
    { name: "1단계", title: "영어 기초와 자기소개", days: "1-10" },
    { name: "2단계", title: "호주 생활 기초", days: "11-20" },
    { name: "3단계", title: "용접 현장 영어", days: "21-30" },
    { name: "4단계", title: "직장 소통과 안전", days: "31-40" },
    { name: "5단계", title: "취업 지원과 면접", days: "41-50" },
    { name: "6단계", title: "호주 정착과 IELTS 실전", days: "51-60" },
  ];

  const rows = [
    ["영어로 자기소개하기", "이름, 직업, 사는 곳을 3문장으로 말합니다.", "name|이름,age|나이,live|살다,work|일하다,welder|용접사,company|회사,experience|경력,Korea|한국,Australia|호주,job|직업", "Hello. My name is Minho. I am a welder from Korea.", "안녕하세요. 제 이름은 민호입니다. 저는 한국 출신 용접사입니다.", "I am + 직업 / I live in + 장소", "Please introduce yourself.", "My name is Minho. I am a welder. I want to work in Australia.", "Tell me about yourself.", "I am a qualified welder from Korea. I have five years of experience."],
    ["용접 경력 설명하기", "근무 기간과 작업 분야를 쉽게 설명합니다.", "year|년,career|경력,welding|용접,factory|공장,construction|건설,steel|강철,pipe|배관,machine|기계,skill|기술,qualified|자격을 갖춘", "I have worked as a welder for five years.", "저는 용접사로 5년 동안 일했습니다.", "I have worked as + 직업 + for + 기간", "How long have you worked as a welder?", "I have worked as a welder for five years. I have pipe welding experience.", "What welding experience do you have?", "I have experience in pipe welding and steel structures."],
    ["현재 업무와 과거 업무", "현재형과 과거형으로 업무를 구분합니다.", "start|시작하다,finish|끝내다,learn|배우다,use|사용하다,make|만들다,check|확인하다,repair|수리하다,cut|자르다,join|연결하다,inspect|검사하다", "I check the equipment and inspect the finished work.", "저는 장비를 확인하고 완성된 작업을 검사합니다.", "I + 현재동사 / I + 과거동사", "What do you do at work?", "I read drawings and weld steel parts. Yesterday, I repaired a frame.", "What did you do in your last job?", "I worked in a factory and repaired steel structures."],
    ["숫자·시간·날짜 듣기", "전화번호와 면접 시간을 정확히 듣습니다.", "13 thirteen|써틴,30 thirty|써티,14 fourteen|포틴,40 forty|포티,15 fifteen|피프틴,50 fifty|피프티,16 sixteen|식스틴,60 sixty|식스티,17 seventeen|세븐틴,70 seventy|세븐티,18 eighteen|에이틴,80 eighty|에이티,19 nineteen|나인틴,90 ninety|나인티", "The interview is on Friday at ten thirty a.m.", "면접은 금요일 오전 10시 30분입니다.", "The + 일정 + is on + 요일 + at + 시간", "When is your interview?", "My interview is on Friday at ten thirty in the morning.", "Can you confirm your phone number?", "Yes. My phone number is zero four one two, seven three five, nine eight six."],
    ["작업장 안전 영어", "필수 안전장비와 금지사항을 말합니다.", "safety|안전,helmet|안전모,gloves|장갑,goggles|보안경,boots|안전화,danger|위험,fire|화재,warning|경고,equipment|장비,accident|사고", "You must wear safety goggles and gloves.", "보안경과 장갑을 반드시 착용해야 합니다.", "You must + 동사 / You must not + 동사", "What safety equipment do you use?", "I use a helmet, gloves, goggles and safety boots.", "Why is safety important?", "Safety is important because welding can be dangerous."],
    ["IELTS Speaking 기초", "대답·이유·예시 순서로 세 문장을 만듭니다.", "enjoy|즐기다,because|왜냐하면,example|예시,practical|실용적인,free time|여가,improve|향상하다", "I enjoy my job because I like making useful things.", "저는 유용한 물건을 만드는 것을 좋아해서 제 일을 즐깁니다.", "대답 + because + 이유 + for example + 예시", "Do you enjoy your job?", "Yes, I do. I enjoy practical work. For example, I make steel parts.", "Why did you become a welder?", "I became a welder because I enjoy making things with my hands."],
    ["General Reading 안전 공지", "공지에서 사람, 날짜, 준비물을 찾습니다.", "notice|공지,attend|참석하다,training|교육,bring|가져오다,employee card|사원증,finish|끝나다", "All new workers must attend safety training on Monday.", "모든 신규 근로자는 월요일 안전교육에 참석해야 합니다.", "All + 사람 + must + 동사", "Who must attend the training?", "All new workers must attend. It starts at nine a.m.", "Can you attend the safety training?", "Yes. I will bring my employee card and safety boots."],
    ["회사에 취업 문의하기", "짧고 정중한 취업 문의문을 만듭니다.", "opportunity|기회,currently|현재,hiring|채용 중인,overseas|해외의,reply|답변,regards|감사 인사", "I am writing to ask about welding job opportunities.", "용접사 채용 기회에 대해 문의하려고 글을 씁니다.", "I am writing to ask about + 명사", "Why are you writing to the company?", "I am asking about welding jobs. I have five years of experience.", "Are you available to work in Australia?", "Yes. I am preparing to move and I am available for an interview."],
    ["위치와 길 안내하기", "작업장 안에서 위치를 묻고 안내합니다.", "left|왼쪽,right|오른쪽,straight|곧장,next to|옆에,opposite|맞은편,between|사이에,behind|뒤에,in front of|앞에,entrance|입구,exit|출구", "The workshop is opposite the main office.", "작업장은 본관 사무실 맞은편에 있습니다.", "The + 장소 + is next to / behind / opposite + 장소", "Where is the safety room?", "It is next to the workshop, opposite the main office.", "Can you find the supervisor's office?", "Yes. I will go straight and turn left at the entrance."],
    ["1단계 종합 복습", "자기소개부터 지원 동기까지 1분 동안 말합니다.", "introduce|소개하다,skill|기술,goal|목표,company|회사,career|경력,confident|자신 있는", "My long-term goal is to live and work in Australia.", "제 장기 목표는 호주에서 거주하며 일하는 것입니다.", "My goal is to + 동사", "Why do you want to work in Australia?", "I want to improve my career and use my welding skills in Australia.", "What is your long-term goal?", "My goal is to become a reliable welder in an Australian company."],
    ["하루 일정 말하기", "일어나는 시간부터 퇴근까지 순서대로 말합니다.", "wake up|일어나다,breakfast|아침식사,leave|출발하다,shift|근무조,lunch|점심,return|돌아오다", "I start my shift at seven and finish at three.", "저는 7시에 근무를 시작하고 3시에 끝냅니다.", "I + 동사 + at + 시간", "What is your daily routine?", "I wake up at five thirty. I start work at seven and finish at three.", "Can you work an early shift?", "Yes. I am used to starting work early."],
    ["대중교통 이용하기", "버스와 기차 시간표를 묻고 이해합니다.", "station|역,platform|승강장,ticket|표,transfer|환승하다,depart|출발하다,arrive|도착하다", "The train leaves platform three at eight fifteen.", "기차는 8시 15분에 3번 승강장에서 출발합니다.", "The + 교통수단 + leaves at + 시간", "How do you travel to work?", "I take the train and then transfer to a bus.", "Will transport be a problem for you?", "No. I checked the timetable and can arrive before my shift."],
    ["집 구하기와 문의하기", "방, 보증금, 입주일을 간단히 묻습니다.", "rent|임대료,room|방,deposit|보증금,available|가능한,inspection|집 보기,move in|입주하다", "The room is available from the first of August.", "그 방은 8월 1일부터 입주할 수 있습니다.", "Is + 명사 + available from + 날짜?", "What kind of home do you need?", "I need a quiet room near public transport.", "When can you move in?", "I can move in from the first of August."],
    ["가격과 물건 사기", "가격, 수량, 결제 방법을 묻습니다.", "price|가격,cost|비용,cheap|저렴한,expensive|비싼,receipt|영수증,card|카드", "These safety boots cost eighty-nine dollars.", "이 안전화는 89달러입니다.", "How much is / are + 명사?", "What do you need to buy?", "I need safety boots and work gloves. I will pay by card.", "Do you have your own safety boots?", "Yes. I bought a new pair yesterday."],
    ["병원 예약하기", "증상을 짧게 설명하고 예약 시간을 잡습니다.", "appointment|예약,pain|통증,doctor|의사,clinic|병원,medicine|약,injury|부상", "I have pain in my shoulder and need an appointment.", "어깨에 통증이 있어서 예약이 필요합니다.", "I have + 증상 / I need + 명사", "How are you feeling today?", "I have a sore shoulder, but I do not have a fever.", "Do you have any work injuries?", "No serious injuries. I always report pain early."],
    ["은행 계좌 만들기", "신분증과 계좌 목적을 설명합니다.", "account|계좌,bank|은행,passport|여권,address|주소,deposit|입금하다,withdraw|출금하다", "I would like to open a bank account.", "은행 계좌를 개설하고 싶습니다.", "I would like to + 동사", "Why do you need a bank account?", "I need an account for my salary and daily payments.", "Can you provide identification?", "Yes. I have my passport and proof of address."],
    ["휴대전화와 인터넷", "요금제와 데이터 용량을 비교합니다.", "plan|요금제,data|데이터,monthly|매월,contract|계약,signal|신호,charge|요금을 청구하다", "This plan includes fifty gigabytes of data each month.", "이 요금제는 매달 50기가바이트 데이터를 포함합니다.", "This plan includes + 수량 + 명사", "How do you use your phone?", "I use it for maps, calls and English study.", "Can we contact you by phone?", "Yes. My phone is always on during business hours."],
    ["날씨와 작업복", "날씨에 맞는 준비와 작업복을 말합니다.", "weather|날씨,hot|더운,cold|추운,rain|비,protective|보호용의,jacket|재킷", "It will be hot tomorrow, so bring extra water.", "내일은 더울 예정이니 물을 더 가져오세요.", "It will be + 날씨, so + 행동", "What weather do you prefer?", "I prefer cool weather because protective clothing is heavy.", "Can you work outdoors in hot weather?", "Yes. I take breaks, drink water and follow safety rules."],
    ["음식 주문하기", "메뉴를 묻고 원하는 음식을 정중하게 주문합니다.", "menu|메뉴,order|주문하다,meal|식사,water|물,without|없이,allergy|알레르기", "Could I have a chicken sandwich without cheese?", "치즈를 빼고 치킨 샌드위치를 주시겠어요?", "Could I have + 음식 + without + 재료?", "What do you usually eat for lunch?", "I usually bring rice, chicken and vegetables.", "Do you have any food allergies?", "No, I do not have any food allergies."],
    ["2단계 생활영어 복습", "생활 속 요청을 정중한 문장으로 바꿉니다.", "request|요청,confirm|확인하다,help|도움,please|부디,problem|문제,solution|해결책", "Could you please confirm the time and address?", "시간과 주소를 확인해 주시겠어요?", "Could you please + 동사?", "What do you do when you need help?", "I ask a clear question and listen carefully to the answer.", "How do you solve a small problem?", "I stay calm, ask for help and check the solution."],
    ["용접 공구 이름 익히기", "기본 공구 이름과 용도를 설명합니다.", "torch|토치,clamp|클램프,grinder|그라인더,hammer|망치,wire brush|철솔,toolbox|공구함", "I use a grinder to clean the metal surface.", "저는 금속 표면을 정리하기 위해 그라인더를 사용합니다.", "I use + 공구 + to + 동사", "Which tools do you use every day?", "I use a torch, grinder, clamps and a wire brush.", "How do you look after your tools?", "I clean them, inspect them and return them to the toolbox."],
    ["기술 도면 읽기", "도면의 치수와 기호를 확인하는 말을 익힙니다.", "drawing|도면,dimension|치수,symbol|기호,measure|측정하다,angle|각도,note|메모", "The drawing shows a ninety-degree angle.", "도면에는 90도 각도가 표시되어 있습니다.", "The drawing shows + 명사", "How do you use technical drawings?", "I check dimensions, symbols and welding notes before I start.", "What do you do if a drawing is unclear?", "I stop and ask the supervisor to confirm it."],
    ["용접 방식 설명하기", "자신이 사용할 수 있는 용접 방식을 말합니다.", "MIG|미그 용접,TIG|티그 용접,arc|아크,process|공정,electrode|용접봉,shielding gas|보호 가스", "I mainly use MIG welding for steel fabrication.", "저는 철강 제작에 주로 미그 용접을 사용합니다.", "I use + 방식 + for + 작업", "Which welding process do you know best?", "I know MIG welding best, and I also have basic TIG experience.", "Which process would you choose for this job?", "I would check the material and drawing before choosing the process."],
    ["재료와 치수 확인하기", "재료 종류, 길이, 두께를 정확히 말합니다.", "steel|강철,stainless|스테인리스,aluminium|알루미늄,length|길이,thickness|두께,millimetre|밀리미터", "This steel plate is ten millimetres thick.", "이 강철판은 두께가 10밀리미터입니다.", "This + 재료 + is + 수치 + millimetres thick", "What material are you working with?", "I am working with a ten-millimetre steel plate.", "How do you confirm measurements?", "I check the drawing and measure the part twice."],
    ["품질 검사하기", "완성된 용접부를 확인하고 결과를 보고합니다.", "quality|품질,inspect|검사하다,crack|균열,surface|표면,finish|마감,standard|기준", "I inspected the weld and found no visible cracks.", "용접부를 검사했으며 눈에 보이는 균열은 없었습니다.", "I inspected + 명사 + and found + 결과", "How do you check your work?", "I inspect the weld, measure the part and compare it with the drawing.", "What does good quality mean to you?", "It means safe, accurate work that meets the required standard."],
    ["결함 보고하기", "문제를 숨기지 않고 위치와 상태를 설명합니다.", "defect|결함,issue|문제,report|보고하다,porosity|기공,incorrect|잘못된,rework|재작업", "I found a small defect near the end of the weld.", "용접 끝부분 근처에서 작은 결함을 발견했습니다.", "I found + 문제 + near + 위치", "What should you do when you find a defect?", "I stop, mark the area and report it to the supervisor.", "Have you ever corrected a welding defect?", "Yes. I removed the defect, prepared the area and completed the rework."],
    ["장비 점검과 유지보수", "작업 전 점검 순서를 간단히 설명합니다.", "maintain|유지하다,cable|케이블,connection|연결부,damage|손상,clean|청소하다,replace|교체하다", "Check the cable and gas connection before starting.", "시작하기 전에 케이블과 가스 연결부를 확인하세요.", "Check + 항목 + before + 동작", "How do you prepare your equipment?", "I check cables, connections and gas, then I clean the work area.", "What do you do with damaged equipment?", "I tag it, stop using it and report it immediately."],
    ["팀으로 작업하기", "동료와 역할을 나누고 진행 상황을 공유합니다.", "team|팀,task|업무,partner|동료,support|지원하다,share|공유하다,complete|완료하다", "My partner prepares the parts while I set up the machine.", "동료가 부품을 준비하는 동안 저는 기계를 설정합니다.", "A does + 업무 while B does + 업무", "Do you prefer working alone or in a team?", "I can work alone, but I enjoy sharing tasks with a safe team.", "How do you support a coworker?", "I communicate clearly, check the plan and help when it is safe."],
    ["근무 교대 인계하기", "다음 근무자에게 완료·미완료 업무를 전달합니다.", "handover|인계,shift|교대,complete|완료된,pending|대기 중인,update|상황 설명,priority|우선순위", "The first frame is complete, but the second one is still pending.", "첫 번째 프레임은 완료됐지만 두 번째는 아직 진행 전입니다.", "A is complete, but B is still pending", "What information is important at handover?", "I explain completed work, safety issues and the next priority.", "Can you give a clear handover?", "Yes. I use short notes and confirm that the next worker understands."],
    ["3단계 현장영어 복습", "공구·도면·품질·팀워크를 연결해 설명합니다.", "prepare|준비하다,follow|따르다,accurate|정확한,safe|안전한,check|확인하다,record|기록하다", "I follow the drawing, check my tools and record the result.", "저는 도면을 따르고 공구를 확인한 뒤 결과를 기록합니다.", "First + 행동, then + 행동, finally + 행동", "Describe your normal welding process.", "First, I read the drawing. Then I prepare and weld. Finally, I inspect the work.", "How do you keep your work safe and accurate?", "I follow procedures, measure carefully and report every problem."],
    ["다시 설명해 달라고 요청하기", "이해하지 못했을 때 정중하게 확인합니다.", "repeat|반복하다,slowly|천천히,mean|뜻하다,understand|이해하다,confirm|확인하다,instruction|지시", "Could you please repeat the last instruction more slowly?", "마지막 지시를 더 천천히 다시 말씀해 주시겠어요?", "Could you please + 동사 + more slowly?", "What do you say when you do not understand?", "I ask the person to repeat or show me the task.", "Are you comfortable asking questions?", "Yes. Asking a clear question prevents mistakes."],
    ["간단한 작업 지시하기", "순서와 안전 주의를 포함해 지시합니다.", "first|먼저,next|다음으로,finally|마지막으로,hold|잡다,secure|고정하다,carefully|주의 깊게", "First, secure the part. Next, check the angle.", "먼저 부품을 고정하세요. 다음으로 각도를 확인하세요.", "First + 동사. Next + 동사. Finally + 동사.", "How would you explain this task?", "First, clean the surface. Next, clamp the part. Finally, check the position.", "Can you train a new worker?", "Yes. I use short steps, demonstrate the task and check understanding."],
    ["작업 지연 보고하기", "지연 이유와 예상 완료 시간을 전달합니다.", "delay|지연,waiting|기다리는 중,delivery|배송,finish|끝내다,estimate|예상하다,available|이용 가능한", "The job is delayed because we are waiting for materials.", "자재를 기다리고 있어서 작업이 지연됐습니다.", "The job is delayed because + 이유", "Why is the job delayed?", "We are waiting for a steel delivery. We expect to finish tomorrow.", "How do you report a delay?", "I explain the reason early and give a realistic completion time."],
    ["사고와 응급처치", "사고 위치와 부상 상태를 빠르게 알립니다.", "emergency|응급상황,injured|다친,first aid|응급처치,ambulance|구급차,bleeding|출혈,conscious|의식이 있는", "A worker is injured near the loading area.", "하역장 근처에서 근로자 한 명이 다쳤습니다.", "A person is + 상태 + near + 장소", "What should you do first in an accident?", "I stop work, make the area safe and call for help.", "Do you know the emergency procedure?", "Yes. I alert the supervisor and contact first aid immediately."],
    ["화재와 대피", "경보, 비상구, 집결지 표현을 익힙니다.", "alarm|경보,fire|화재,exit|출구,evacuate|대피하다,assembly point|집결지,extinguisher|소화기", "When the alarm sounds, use the nearest safe exit.", "경보가 울리면 가장 가까운 안전한 출구를 이용하세요.", "When + 상황, + 행동", "Where is the assembly point?", "It is outside the main gate, next to the visitor car park.", "What would you do during a fire alarm?", "I would stop work, evacuate and report to the assembly point."],
    ["툴박스 미팅 참여하기", "위험요소와 오늘의 작업을 짧게 공유합니다.", "meeting|회의,hazard|위험요소,plan|계획,discuss|논의하다,control|통제하다,question|질문", "Today we will discuss heat, fumes and ventilation.", "오늘은 열, 연기, 환기에 대해 논의합니다.", "Today we will discuss + 주제", "What do you say at a toolbox meeting?", "I share hazards, ask questions and confirm the work plan.", "Why are toolbox meetings useful?", "They help the team identify risks before work starts."],
    ["휴가와 병가 요청하기", "날짜와 이유를 정중하게 전달합니다.", "leave|휴가,sick|아픈,request|요청,approve|승인하다,medical certificate|진단서,return|복귀하다", "I would like to request leave next Friday.", "다음 주 금요일에 휴가를 요청하고 싶습니다.", "I would like to request + 명사 + on + 날짜", "Why do you need leave?", "I have a medical appointment and will return on Monday.", "How early do you request planned leave?", "I submit the request as early as possible."],
    ["근무표와 초과근무", "근무 가능 시간과 제한을 분명히 말합니다.", "roster|근무표,overtime|초과근무,weekend|주말,available|가능한,swap|교대하다,notice|통보", "I am available for overtime on Saturday morning.", "토요일 오전에는 초과근무가 가능합니다.", "I am available for + 근무 + on + 날짜", "When are you available to work?", "I can work weekdays, weekends and rotating shifts.", "Can you work overtime at short notice?", "Sometimes, yes. I need to check my transport and family schedule."],
    ["직장 의견 차이 해결하기", "감정을 낮추고 사실과 해결책을 말합니다.", "disagree|동의하지 않다,calm|침착한,listen|듣다,explain|설명하다,respect|존중하다,agree|합의하다", "We disagreed about the plan, so we checked the drawing together.", "계획에 의견 차이가 있어 함께 도면을 확인했습니다.", "We disagreed about + 문제, so + 해결", "How do you handle disagreement?", "I stay calm, listen and use facts to find a safe solution.", "Tell me about a conflict at work.", "A coworker and I had different ideas. We checked the standard and agreed on one method."],
    ["4단계 직장소통 복습", "질문·지시·보고·의견 조율을 한 흐름으로 연습합니다.", "communicate|소통하다,clearly|명확하게,early|일찍,problem|문제,procedure|절차,solution|해결책", "Clear communication helps us prevent mistakes and accidents.", "명확한 소통은 실수와 사고를 예방하는 데 도움이 됩니다.", "명사 + helps us + 동사", "Why is communication important at work?", "It helps the team work safely, solve problems and finish on time.", "How would your supervisor describe you?", "My supervisor would say I communicate clearly and report problems early."],
    ["영문 이력서 핵심", "직무명, 경력, 기술을 짧은 문구로 작성합니다.", "resume|이력서,summary|요약,employment|고용,qualification|자격,reference|추천인,achievement|성과", "My resume includes five years of welding experience.", "제 이력서에는 5년의 용접 경력이 포함되어 있습니다.", "My resume includes + 경력/기술", "What information is on your resume?", "It includes my qualifications, work history and welding skills.", "What is your main qualification?", "I hold a welding qualification and have strong fabrication experience."],
    ["커버레터 작성하기", "지원 직무와 강점을 연결해 세 문장을 씁니다.", "apply|지원하다,position|직위,company|회사,suitable|적합한,contribute|기여하다,available|가능한", "I am applying for the welder position advertised online.", "온라인에 공고된 용접사 직무에 지원합니다.", "I am applying for + 직무", "Why are you applying for this position?", "The role matches my experience and gives me a chance to grow.", "What can you contribute to our company?", "I can contribute safe work, reliable attendance and practical welding skills."],
    ["전화 사전 면접", "전화로 이름, 지원 직무, 가능 시간을 확인합니다.", "caller|전화한 사람,application|지원서,available|가능한,interview|면접,confirm|확인하다,schedule|일정", "I am calling about your application for the welder role.", "용접사 직무 지원서와 관련해 전화드렸습니다.", "I am calling about + 명사", "Are you available for an interview tomorrow?", "Yes. I am available after two p.m.", "Can you briefly describe your experience?", "I have five years of factory and pipe welding experience."],
    ["면접에서 강점 말하기", "강점을 근거와 함께 설명합니다.", "strength|강점,reliable|믿을 수 있는,careful|꼼꼼한,punctual|시간을 지키는,quality|품질,consistent|꾸준한", "My main strength is careful and consistent work.", "제 주요 강점은 꼼꼼하고 꾸준한 작업입니다.", "My main strength is + 명사", "What are your strengths?", "I am reliable, safety-focused and careful with measurements.", "Can you give an example of your strength?", "I check every drawing and measurement before welding, which reduces rework."],
    ["약점과 학습 태도", "약점을 솔직하게 말하고 개선 행동을 붙입니다.", "weakness|약점,nervous|긴장한,practice|연습하다,improve|개선하다,feedback|피드백,course|과정", "I sometimes feel nervous in English, so I practise every day.", "영어로 말할 때 가끔 긴장해서 매일 연습합니다.", "I sometimes + 약점, so I + 개선 행동", "What is one weakness you are improving?", "My English is still basic, but I study daily and ask for feedback.", "How do you learn a new skill?", "I watch a demonstration, practise slowly and ask someone to check my work."],
    ["문제 해결 경험", "상황·행동·결과 순서로 짧게 답합니다.", "problem|문제,cause|원인,action|행동,result|결과,solve|해결하다,prevent|예방하다", "The parts did not fit, so I checked the measurements again.", "부품이 맞지 않아 치수를 다시 확인했습니다.", "문제 + so + 행동 + and + 결과", "Tell me about a problem you solved.", "A frame was out of position. I stopped, measured it and corrected the setup.", "What did you learn from that problem?", "I learned to confirm the setup before starting the weld."],
    ["안전 면접 답변", "위험 발견부터 보고까지 순서대로 답합니다.", "risk|위험,identify|식별하다,control|통제하다,PPE|개인보호구,procedure|절차,report|보고하다", "I identify the risk, use the correct PPE and follow the procedure.", "위험을 확인하고 적절한 보호구를 사용하며 절차를 따릅니다.", "I + 행동, + 행동 and + 행동", "How do you manage safety risks?", "I inspect the area, use PPE and stop if conditions are unsafe.", "What would you do if a coworker ignored a safety rule?", "I would warn them respectfully and report the risk if it continued."],
    ["팀워크 면접 답변", "역할, 소통, 결과를 포함해 팀 경험을 말합니다.", "cooperate|협력하다,role|역할,deadline|마감일,communicate|소통하다,assist|돕다,success|성공", "Our team shared the tasks and finished before the deadline.", "우리 팀은 업무를 나눠 마감 전에 끝냈습니다.", "Our team + 행동 and + 결과", "Tell me about a successful team project.", "We built several frames. I handled welding and checked progress with the fitter.", "What role do you take in a team?", "I complete my task, communicate early and help others when needed."],
    ["급여와 근무조건 묻기", "면접 말미에 정중하게 조건을 확인합니다.", "salary|급여,hourly rate|시급,condition|조건,probation|수습기간,benefit|복리후생,uniform|유니폼", "Could you explain the shift pattern and hourly rate?", "근무 형태와 시급을 설명해 주시겠어요?", "Could you explain + 명사?", "What would you like to know about the role?", "I would like to know the shift pattern, start date and training process.", "What salary do you expect?", "I am open to the standard rate for this role and my level of experience."],
    ["취업 면접 종합 연습", "자기소개부터 마지막 질문까지 3분 면접을 완성합니다.", "prepare|준비하다,answer|답변,example|예시,question|질문,confident|자신 있는,thank|감사하다", "Thank you for the opportunity to interview today.", "오늘 면접 기회를 주셔서 감사합니다.", "Thank you for + 명사", "Why should we hire you?", "I have relevant experience, a strong safety mindset and a reliable work attitude.", "Do you have any questions for us?", "Yes. What training and support do you provide for new workers?"],
    ["호주 직장 문화", "시간 준수, 직접적인 소통, 존중을 설명합니다.", "punctual|시간을 지키는,direct|직접적인,respectful|존중하는,diverse|다양한,fair|공정한,feedback|피드백", "Australian workplaces value punctual and respectful communication.", "호주 직장은 시간 준수와 존중하는 소통을 중요하게 생각합니다.", "Workplaces value + 명사", "What is important in a workplace culture?", "Respect, clear communication and fair treatment are important to me.", "How do you work with people from different backgrounds?", "I listen, speak respectfully and focus on the shared task."],
    ["세금번호와 급여 서류", "기본 고용 서류의 목적을 이해합니다.", "tax|세금,number|번호,payroll|급여 관리,form|양식,identity|신원,submit|제출하다", "Please submit your tax file number form to payroll.", "세금번호 양식을 급여 담당 부서에 제출하세요.", "Please submit + 서류 + to + 부서", "What employment documents do you need?", "I need identification, bank details and the required payroll forms.", "Can you complete online forms?", "Yes. I can follow instructions and ask for help if a form is unclear."],
    ["퇴직연금 기본 영어", "급여명세서에서 연금 관련 표현을 찾습니다.", "superannuation|퇴직연금,employer|고용주,contribution|납입금,fund|기금,payslip|급여명세서,choice|선택", "The employer pays superannuation into your chosen fund.", "고용주는 선택한 기금에 퇴직연금을 납입합니다.", "The employer pays + 명사 + into + 장소", "What do you check on a payslip?", "I check my hours, pay, tax and superannuation details.", "Do you understand this payroll information?", "I understand the main points, but I would ask payroll about unclear details."],
    ["임대와 공과금", "집세, 전기, 물, 인터넷 책임을 확인합니다.", "utility|공과금,electricity|전기,water|물,internet|인터넷,included|포함된,tenant|세입자", "Water is included, but the tenant pays for electricity.", "수도요금은 포함되지만 전기요금은 세입자가 냅니다.", "A is included, but B pays for C", "Which bills are included in the rent?", "Water is included. I need to pay for electricity and internet.", "Can you provide a rental reference?", "Yes. I can provide contact details for my previous landlord."],
    ["지역 서비스 이용하기", "도서관, 주민센터, 긴급하지 않은 도움을 찾습니다.", "library|도서관,council|지역 의회,service|서비스,community|지역사회,information|정보,centre|센터", "The community centre offers free English classes on Tuesday.", "지역센터는 화요일에 무료 영어 수업을 제공합니다.", "The + 장소 + offers + 서비스 + on + 요일", "Which community service would help you?", "A local English class and library would help me settle in.", "How do you find reliable local information?", "I check official service websites or ask the local council."],
    ["비자·신분 서류 영어", "공식 문서에서 이름, 날짜, 요청사항을 확인합니다.", "document|서류,visa|비자,expiry|만료,passport|여권,application|신청,official|공식적인", "Check that your passport name matches every application document.", "여권 이름이 모든 신청 서류와 일치하는지 확인하세요.", "Check that + 문장", "How do you organise important documents?", "I keep clear copies and check names, dates and reference numbers.", "What would you do if official information was unclear?", "I would check the official source or ask a qualified professional."],
    ["IELTS Listening 미니 실전", "Section 1 형식에서 이름·시간·번호를 받아씁니다.", "booking|예약,reference|참조번호,available|가능한,postcode|우편번호,spell|철자를 말하다,confirm|확인하다", "Your booking reference is B seven four nine, and the class starts at six thirty.", "예약번호는 B749이고 수업은 6시 30분에 시작합니다.", "Your + 정보 + is + 세부 내용", "What details did you hear?", "I heard the booking number and the starting time.", "Could you spell your family name?", "Yes. It is K-I-M."],
    ["General Reading 미니 실전", "짧은 직장 공지에서 조건과 마감일을 찾습니다.", "deadline|마감일,eligible|자격이 있는,apply|신청하다,requirement|요건,contact|연락하다,before|전에", "Workers must submit the training form before Friday afternoon.", "근로자는 금요일 오후 전에 교육 양식을 제출해야 합니다.", "People must + 동사 + before + 시간", "What is the deadline?", "The form must be submitted before Friday afternoon.", "Are you eligible for this training?", "Yes. I meet the stated requirements and can attend."],
    ["General Writing 미니 실전", "회사에 보내는 70단어 내외의 간단한 요청문을 씁니다.", "email|이메일,subject|제목,reason|이유,detail|세부사항,request|요청,closing|맺음말", "I am writing to request a change to my training date.", "교육 날짜 변경을 요청하려고 글을 씁니다.", "I am writing to request + 명사", "What should a clear email include?", "It should include the reason, important details and a polite request.", "Can you write a short workplace email?", "Yes. I use a clear subject, short sentences and a polite closing."],
    ["Speaking·면접 최종 평가", "IELTS 답변과 취업 면접 답변을 연결해 5분 동안 말합니다.", "progress|진전,challenge|도전,achievement|성과,future|미래,ready|준비된,reliable|믿을 수 있는", "I have improved my English and I am ready to keep learning.", "영어가 향상됐고 계속 배울 준비가 되어 있습니다.", "I have + 과거분사 and I am ready to + 동사", "How has this course helped you?", "I can introduce myself, discuss work and handle simple daily situations.", "Why are you ready for an Australian workplace?", "I bring welding experience, a safety-first attitude and a strong willingness to learn."],
  ];

  const examFocus = [
    "Listening Section 1: 이름·숫자·시간 포착",
    "Speaking Part 1: 짧고 직접적인 답변",
    "General Reading: 공지·표지·안내문 찾기",
    "General Writing: 목적이 분명한 짧은 문장",
  ];

  const days = rows.map(function (row, index) {
    const day = index + 1;
    const phaseIndex = Math.floor(index / 10);
    return {
      day: day,
      phase: phases[phaseIndex],
      title: row[0],
      goal: row[1],
      vocabulary: row[2].split(",").map(function (item) {
        const parts = item.split("|");
        return { en: parts[0], ko: parts[1] };
      }),
      listening: { en: row[3], ko: row[4] },
      pattern: row[5],
      speaking: { question: row[6], answer: row[7] },
      interview: { question: row[8], answer: row[9] },
      examFocus: examFocus[index % examFocus.length],
    };
  });

  window.IELTS11_BEGINNER_PHASES = phases;
  window.IELTS11_BEGINNER_DAYS = days;
})();
